alphagov/emergency-alerts-govuk

src/how-alerts-work.html
src/index.html
src/opt-out.html
src/reasons-you-might-get-an-alert.html
src/when-you-get-an-alert.html
templates/_layout.html

There are a few places where our approach to when to capitalise Emergency Alerts and when not to looks a bit weird.
This PR fixes that by making it more explicit when we’re talking about the service name.
It includes changes to page titles and navigation, so it *might* break some smoke tests.
`Emergency Alerts`
* landing page title
* breadcrumb for landing page
* footer menu heading
* only if we’re explicitly talking about the service, for example: ‘the Emergency Alerts service’
`emergency alerts` or `emergency alert`
* everywhere else
`alerts` or `alert`
* only use after ‘emergency alerts’ to reduce repetition and improve readability

Tidy up use of brand name

---

templates/components/example.html

Internet Explorer and Microsoft Edge up to version 13 treat SVGs as interactive elements and include them in the `tabindex` unless they have `focusable="false"`.
Add `focusable="false"` to the example SVG so that it's not included when tabbing in these browsers – at the minute if you tab forwards from the 'What happens when you get an alert' link it gets focused, but does not have a visible focus state so the focus appears 'lost'.

Remove example SVG from tab order in IE / Edge

---

src/privacy-notice.html

This PR updates the privacy statement to:
- amend information about taking part in future user research
- make the use of the Emergency Alerts brand name consistent with the rest of the site content
- update the last reviewed date

Update privacy notice

---

src/when-you-get-an-alert.html

This PR updates the iPhone instructions based on feedback received on Twitter:
> Can I make a suggestion for http://gov.uk/alerts/when-you-get-an-alert? The iPhone instructions say “swipe down on the Home Screen”, but that’ll open Spotlight search if you swipe in the middle. A more reliable instruction would be “swipe down from the top of the screen”. Nice pages, very clear!
Would be great if at least 1 iPhone user could check this.

Update iPhone instructions

---

src/assets/stylesheets/components/example.scss
templates/components/example.html

In IE9-11, it looks like removing the height and width attributes from the SVG made it render much smaller than it should be.
This replaces those attributes and rewrites the mobile breakpoint so it matches the intended size while maintaining the same aspect ratio.
|Desktop|Mobile|
|---|---|
|<img width="996" alt="with_max_height_desktop" src="https://user-images.githubusercontent.com/87140/118886271-a08a1d80-b8f0-11eb-92a6-5b80476d233d.png">|<img width="375" alt="iphone_8_chrome_emulation" src="https://user-images.githubusercontent.com/87140/118886299-a97aef00-b8f0-11eb-895e-09f377ece35d.png">|

Fix visual bug with example SVG in IE11

---

src/how-alerts-work.html
src/opt-out.html

This PR updates the introduction to the opt out page.
We’re making this change because it’s no longer true to say that users can opt out of all alerts.
The 25 May test will be sent on the ‘severe’ and ‘government’ channels – the latter of which is mandatory.
Currently we do not mention the ‘government’ channel because:
- explaining the different channels makes the content more complex
- the policy decision about if and when ‘government’ alert will not happen until after the East Suffolk test
Until that decision is made we do not want to introduce an explanation of the channels. However, we should update the content so it’s closer to the statement given to the press, which said:
> “It will be possible to opt-out of some alerts through the phone's settings. However, the most important …

Update content for ‘How to opt out of emergency alerts’

---

Makefile
build.py
lib/alert.py
lib/alert_date.py
lib/alerts.py
lib/utils.py
src/alert.html
tests/conftest.py
tests/test_alert.py
tests/test_alert_date.py
tests/test_alerts.py
tests/test_utils.py

https://www.pivotaltracker.com/story/show/178198202
In attempting to add a previous alerts feature I got stuck
because the "is_alert_current" function could only be used
for a limited time, before any rendering took place.
This PR makes a broad refactoring to cut down on the number
of utilities, so all the data and functionality is easier to
find, and always works together.
Please see the commit messages for more details.

Refactor data handling to support previous alerts

---

src/planned-tests.html

We’ve been asked to add this by the comms agency to help with partner outreach.

Add content of test alert to planned alerts page

---

Makefile

This matches where we check Python code with `flake8`. It means you don’t have to spend time waiting for the lint task to run every time you want to rebuild the site.

Lint frontend code as part of test, not build step

---

build.py
lib/alert.py
lib/alerts.py
src/alert.html
src/current-alerts.html
src/index.html
src/past-alerts.html
templates/_layout.html
templates/components/alert.html
templates/components/alerts_icon.html
templates/components/banner.html
tests/test_alert.py
tests/test_alerts.py

https://www.pivotaltracker.com/story/show/178198202
I've tried to limit the number of decisions in this PR. Once
this is merged, it should then be a safe and simpler task to
iterate the design, noting that the page won't have content
until the first alert expires.
Things to (ideally) do in future work:
- Rebase https://github.com/alphagov/notifications-govuk-alerts/pull/65 to support "paragraphize" on the previous alerts page.
- Decide if we want to show author/timing info in the list of previous/current alerts
- Decide if we want to modify the single alert page to clearly show it's expired (we probably want to do more than change the colour of the icon, so I've just left it untouched in this PR)
| New page  | Expired alert page (breadcrumb) |
| ------------- | ------------- |
| <img …

Add a minimal page for previous alerts

---

src/how-alerts-work.html
src/opt-out.html
src/when-you-get-an-alert.html

We’ve been informed that emergency alerts aren’t compatible with iPads.

Remove references to iPads

---

src/when-you-get-an-alert.html

This PR updates the list of things that can happen when you get an emergency alert.
In previous trials, a higher proportion of devices than expected read the alert aloud. We should make users aware of this.
We’ve also changed ‘will’ to ‘may’, because not all devices behave the same way when they get an alert.

Update what happens when you get an emergency alert

---

src/alert.html

Replicates the work done in https://github.com/alphagov/notifications-govuk-alerts/pull/44

Make spacing between double details tighter

---

data.yaml
lib/alerts.py
tests/test_alerts.py

The most recent time the site will be updated with new information is when the most recent alert was broadcast.
This commit sets that date automatically, so we don’t have to update it manually (something we might forget to do).

Set the last updated automatically

---

templates/components/alert.html

Paragraphs inside paragraphs aren’t valid HTML. They also introduce extra spacing.
This commit removes the containing paragraph (`paragraphize` will always give us at least one paragraph) and adjust the spacing to suit.
Before | After
---|---

Fix double nested paragraph

---

src/404.html
src/alert.html
src/assets/stylesheets/_extensions.scss
src/assets/stylesheets/components/survey.scss
src/assets/stylesheets/main.scss
src/current-alerts.html
src/how-alerts-work.html
src/index.html
src/opt-out.html
src/planned-tests.html
src/privacy-notice.html
src/reasons-you-might-get-an-alert.html
src/when-you-get-an-alert.html
templates/_layout.html
templates/components/survey.html

Adds a survey component, loosely based on [GOVUK's feedback component](https://components.publishing.service.gov.uk/component-guide/feedback).
https://www.pivotaltracker.com/story/show/177726051
|Desktop|Mobile|
|---|---|
|<img width="1090" alt="survey_desktop" src="https://user-images.githubusercontent.com/87140/118981788-a6c0de00-b972-11eb-888d-730955ef1177.png">|<img width="374" alt="survey_mobile" src="https://user-images.githubusercontent.com/87140/118981816-acb6bf00-b972-11eb-9179-1f90d8ceed59.png">|
Currently contains fake content so I'm leaving this in draft until @karlchillmaid can write something real for it.
I've checked on all browsers in our matrix and the link in it has been checked against the [GOVUK feedback component's accessibility …

Add survey component

---

src/alert.html

This is consistent with who we are saying sent the alert in comms
> **government**
> Lower case unless it’s a full title. For example: ‘UK government’, but ‘Her Majesty’s Government of the United Kingdom of Great Britain and Northern Ireland’.
— https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#government

Say ‘UK government’ sent the alert

---

src/assets/stylesheets/components/survey.scss

We don’t need this because we’re using a non-breaking space in the HTML to control wrapping instead.

Remove accidentally committed CSS

---

lib/alert_date.py
src/alert.html
tests/test_alert_date.py

This pull request makes the way we show dates and times conform to the GOV.UK styleguide<sup>1</sup>. It also makes the date on the page for a single alert absolute, not relative.
***
1. https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#times

Format dates and times in GOV.UK style

---

src/alert.html

The content on past alert pages needs to make clear that the alert is not about a current emergency.
All we can say for certain is that the alert has stopped sending. The emergency itself may be ongoing.
We agreed to prioritise the date and time over the body of the alert, reversing the order of priority of information on current alerts.
---
---
Discussion: https://docs.google.com/document/d/1regPI_sAYQsHxUxgjQ3_nLiQ_E_qQkKiG4AIKATD0p8/edit#

Add expired date to past alerts

---

data.yaml

This PR updates the headline field of the test alert to `Emergency alert`.
`Emergency alert` is closer to the user experience and consistent with the rest of the content on gov.uk/alerts.

Update headline of the test alert

---

src/index.html
src/planned-tests.html

_Should not be merged until after 1pm on Tuesday 25 May._
***
So that this page doesn’t become outdated this commit replaces details of the East Suffolk test (which will be on the previous alerts page) with details of the upcoming test in Reading.
The date of this test has been given to the media<sup>1</sup>, so it’s OK for us to give the date publicly. We can add more detail closer to the day.
---
1. https://www.bbc.co.uk/news/uk-politics-57145675

Add details of planned test in Reading

---

tests/test_data_yaml.py

So that they respect daylight saving time changes.
This implements following decision:
Make all timestamps iso 8601, local to the Europe/London with an explicit offset*.
For example: 10:00am on 12 March 2021, which is outside of British Summer Time (BST)
would be:
2021-03-12T10:00+00:00
Whereas 10:00am on 12 May 2021, which is inside BST would be:
2021-05-12T10:00+01:00
This would be enforced by:
a test that checks all the timestamps in data.yaml
an example alert which explains the format used and variations to consider
*following the formatting rules in
https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators
Pivotal ticket: https://www.pivotaltracker.com/story/show/178198145

Test that dates in alert data have correct time offsets

---

templates/components/meta_tags.html

At the moment if you see gov.uk/alerts shared on twitter we do not have
an open graph image for it.
Example: https://twitter.com/ollietheantijab/status/1397235543423979524
I believe the problem is that our open graph url is relative rather than
absolute.
https://stackoverflow.com/questions/9858577/open-graph-can-resolve-relative-url
By changing it to an absolute URL I think this will fix it and it will
start appearing.

Fix open graph image not showing due to relative path

---

src/alert.html

It's no longer used, since the date it converted was converted to the full form, in https://github.com/alphagov/notifications-govuk-alerts/pull/88.

Remove relative-dates JS from alert page

---

src/assets/stylesheets/_extensions.scss
src/opt-out.html
src/planned-tests.html
src/reasons-you-might-get-an-alert.html
src/when-you-get-an-alert.html
templates/_layout.html

This PR adds:
- information about the ongoing operator tests to the _Planned tests_ page
- a link to _Planned tests_ from the footer
- links to _Planned tests_ from relevant content on other pages
- updated opt-out instructions for test messages on the _Opt out_ page
- a link from _Planned tests_ to the _Opt out_ page

Add details of ongoing operator tests 

---

src/how-alerts-work.html

This PR adds content for users who cannot receive emergency alerts – either because their device is not compatible, or they do not have a phone or tablet.

Add content for users who cannot receive alerts

---

src/planned-tests.html

Operator tests will be happening sooner than the Reading test, so we should lead with those.

Put planned tests ahead of Reading test

---

src/when-you-get-an-alert.html

The PR adds content about (and links to) current and past alerts on GOV.UK.
We removed this line when we launched the MVP site, but now the current and past alerts pages are live we can reinstate it.

Add content about current and past alerts

---

templates/components/alerts_icon.html

I noticed that the alert icon image, used as a fallback for the SVG version, is broken in IE8 (which uses it due to lack of support for SVG).
Looks like the fallback image has classes intended for the example image on the home page (of the phone). This fixes it to instead have the same classes as the SVG it replaces.

Fix fallback image for alert icon

---

src/assets/javascripts/sharing-button.mjs
tests/javascripts/sharing-button.test.js
tests/javascripts/support/helpers.js

Adds tests for the sharing button JS.
Part of https://www.pivotaltracker.com/story/show/177597156. This should complete the 'test the JavaScript works' task because we are not testing GOVUK Frontend code.
To run these tests only, use this command:
`npx jest --config tests/javascripts/jest.config.js tests/javascripts/sharing-button.test.js`
This pull request also includes:
- adding checks for copy-to-clipboard support instead of assuming it exists if the Web Share API doesn't
- updates the RegExp used to trim the URL string to use the `String.prototype.trim` polyfill from MDN

Add JS tests for sharing button

---

tests/test_content_security_policy_sha.py
tests/test_csp_sha.py

We use the GOVUK Frontend library template.html
file as the base layout of our pages. It includes
an inline script which our Content Security Policy
allows by referencing a sha256 of its contents.
This adds a test to check the script's contents
match the sha256. If this test fails, the sha256
has changed and so the sha256 in our Content
Security Policy will need to be updated to the new
value.
Part of this story:
https://www.pivotaltracker.com/story/show/177597156
The Content Security Policy is added here:
https://github.com/alphagov/notifications-broadcasts-infra/blob/main/terraform/modules/govuk-alerts-website/files/main.py
It is tested here:
https://github.com/alphagov/notifications-broadcasts-infra/blob/main/terraform/modules/govuk-alerts-website/files/test_inject_headers.py
Both …

Add test for inline script

---

package-lock.json
package.json
src/assets/stylesheets/_govuk_frontend.scss

For more details see https://github.com/alphagov/govuk-frontend/releases/tag/v3.12.0

Update GOV.UK Frontend to get new link styles

---

src/index.html
src/planned-tests.html

It’s over now.
Also makes it clearer that most people probably won’t get an alert during one of these tests.

Remove today’s test from the planned tests page

---

src/opt-out.html
src/reasons-you-might-get-an-alert.html
src/when-you-get-an-alert.html
tests/test_local_links.py

They won’t have the correct colour or nice underline without this class.

Fix links that don’t have the govuk-link class

---

src/planned-tests.html

To differentiate it from the planned operator test, which is only for Android devices.

Make devices explicit for the Reading test

---

src/index.html
src/planned-tests.html

It’s over now.
This PR should be merged at the end of today (22 June)

Remove the 22 June test from planned tests page

---

src/planned-tests.html

It’s pointing to the wrong place, which can cause the wrong preview to show when the link is shared on social media.

Fix og:url for planned tests page

---

templates/components/meta_tags.html

Currently our specified image is not being shown on twitter cards, for
example in https://twitter.com/msuxg/status/1407254592333697024
In our html we currently have
```
<meta property="og:image" content="https://www.gov.uk/alerts/assets/images/opengraph-image.png?f86f1d0dd106bfbcd8ad1ee5ea68e75e">
...
<meta property="og:image" content="/assets/images/govuk-opengraph-image.png">
```
where the first is the image we want to show and the second is html
added by the GOV.UK Frontend.
https://github.com/alphagov/govuk-frontend/blob/v3.12.0/src/govuk/template.njk#L26
Note the second meta image currently 404s for us because it is
a relative url rather than an absolute url.
Twitter should be following the spec of open graph, where the first
image is given preference and it ignores the second - …

Fix twitter card not showing our image

---

src/reasons-you-might-get-an-alert.html

We’ve been asked to make the link to the survey more prominent for the Reading test.
The ‘Reasons you might get an alert’ page seems like the most appropriate place to do this.

Add survey link to the ‘Reasons you might get an alert’ page

---

src/reasons-you-might-get-an-alert.html

This PR updates link text on the _Reasons you might get an alert_ page to make it:
* sound better
* more consistent with the banner link content

Small content update to improve link text

---

src/index.html
src/planned-tests.html

https://www.pivotaltracker.com/story/show/178622042
We should keep the page in case it's been indexed or bookmarked,
as well as to confirm what the future plans are.

Remove planned tests banner and content

---

data.yaml

They appear to be shown in the order they are in the yaml file
The quickest way to fix this is to swap the order. It works locally.
In time we may want a smarter way for this though where they are sorted
automatically

Reorder past alerts

---

build.py
data.yaml
lib/alert.py
lib/alert_date.py
lib/alerts.py
src/mobile-network-operator-tests.html
src/opt-out.html
src/past-alerts.html
templates/components/alert.html

So if you have received one of these we are acknowledging it happened, even if we’ve taken it off the planned tests page.
New page structure looks like:

Add previous operator tests to the previous alerts page

---

data.yaml
src/index.html
src/planned-tests.html

Move the 2 July operator test to the past alerts page

---

data.yaml
lib/alert.py
src/alert.html

Small contribution to: https://www.pivotaltracker.com/story/show/178774818
This is only used for "alert" messages (noting that the "operator"
ones don't have their own page [1]) and is always set to the same
text. Although this field is shown in the UI [2] it's not actually
used [3] or stored in the DB.
[1]: https://github.com/alphagov/notifications-govuk-alerts/blob/db69aa1e9db89ec063733a0e48d99a0cf5fb71a6/build.py#L48
[2]: https://github.com/alphagov/notifications-admin/blob/d414e6d345930f9a47ed1fc2fe0faf99d3769840/app/templates/views/broadcast/write-new-broadcast.html#L22
[3]: https://github.com/alphagov/notifications-admin/blob/d414e6d345930f9a47ed1fc2fe0faf99d3769840/app/main/views/broadcast.py#L147-L151

Remove redundant 'headline' field

---

build.py
data.yaml
lib/alert.py
lib/alerts.py
requirements_for_test.txt
src/alert.html
src/current-alerts.html
src/past-alerts.html
templates/components/alert.html
tests/conftest.py
tests/lib/test_alert.py
tests/lib/test_alerts.py
tests/src/test_alert.py
tests/src/test_current_alerts.py
tests/src/test_index.py
tests/src/test_past_alerts.py
tests/test_all_pages.py
tests/test_content_security_policy_sha.py

https://www.pivotaltracker.com/story/show/178774818
This is part of the work we need to do to replace (most of) the data.yaml
file with an API. Please see the commit messages for more details.
One outstanding question is whether we should ever show messages on the test
channel. Currently we don't have any, but if we did they would appear like any
other alert. We don't need to answer this question here, and I've made a note
on the card to make a decision as part of writing the API.

Fix and standardise filtering on alert types

---

data.yaml

The Admin app has a standalone "Sizewell" area for this alert. We
decided to change both apps to just say "East Suffolk", to match
the level of precision we expect to have for standard areas [1],
but still customising it for the alert.
[1]: https://github.com/alphagov/notifications-admin/pull/3980

Rename demo area to match Admin app

---

src/index.html
src/planned-tests.html

O2 are performing resilience tests requiring messages to be sent on the operator channel to public cells on the live network.
This change updates current alerts to display information about the tests.

Add 5 August planned operator test to alerts page

---

src/index.html
src/planned-tests.html

Reverts changes regarding the planned test notifications sent on August 5.

Remove August 5 Planned Tests

---

src/assets/stylesheets/components/responsive-embed.scss
src/assets/stylesheets/main.scss
src/index.html

We’ve agreed with the comms folk that this video should go in the empty space on the homepage.
I’ve borrowed the responsive embed CSS from the admin app to make sure the video displays properly on different device sizes.
Hosted on Youtube, but served via their cookie-free domain so we don’t need to add a cookie policy.
***
https://www.youtube.com/watch?v=9yLd2AjGzYI

Add explainer film to the homepage

---

src/assets/stylesheets/components/responsive-embed.scss

Responsive embed _wrapper_ was renamed to _content_ in e1f0e13. Some references were missed causing minor style issues and 0 iframe content height.
**Before**
**After**

Rename all references to responsive embed wrapper

---

app/config.py
manifest.yml.j2

https://www.pivotaltracker.com/story/show/178801234
Resolves: https://github.com/alphagov/notifications-govuk-alerts/pull/151#discussion_r688341788
This is firstly because the startup command referred to a package
('main') that didn't exist, which we also then tried to import.

Fix Celery worker crashing after deployment

---

Makefile
app/__init__.py
app/commands.py
tests/app/test_commands.py

https://www.pivotaltracker.com/story/show/178801234
This is intended to be run straight after a deployment. A downside
of 'cf run-task' is that it's asynchronous, so just like a normal
app crashing, we'll need to have some other alerting in place so
we learn if the publish task failed.

Add command / task to republish alerts

---

README.md
docs/architecture.md

https://www.pivotaltracker.com/story/show/178801234
The diagram is the important part, while the text is more about the
history of the app (to help explain potential weirdnesses). In future
we may want to rewrite this to simply state the architecture and how
the app is organised, but the story format seems more appropriate as
we continue to make changes towards the architecture in the diagram.
Command to generate the diagrams [1]:
cat arch.dot | docker run -i tsub/graph-easy
👉 [Rendered version](https://github.com/alphagov/notifications-govuk-alerts/blob/add-arch-doc-178801234/docs/architecture.md)
[1]: https://gist.github.com/benthorner/1901916c925e1b60cd14728c9aa5d332

Add architecture doc

---

data.yaml
lib/alert.py
src/alert.html
templates/components/alert.html
tests/conftest.py
tests/src/test_current_alerts.py
tests/src/test_past_alerts.py

https://www.pivotaltracker.com/story/show/178986763
Previously this was a separate list due to some confusion about the
"areas" field being a list (of lists). In reality it's just a dict
with a "simple_polygons" field, so we can co-locate aggregate area
names inside it as another field.

Simplify aggregate area names to be part of areas

---

src/index.html
src/planned-tests.html

Adds planned test information to website in advance of o2 resilience tests.
**Don't merge until 23/8/2021 am**

Add planned 23 August operator test information [Merge 23/8 am]

---

app/templates/views/index.html
app/templates/views/planned-tests.html
data.yaml

Planned test is now complete. We can remove the banner and info.
This reverts commit 10b04284722973a960984d21e4bc12ec2dcc1fee, reversing
changes made to 27be533d718c35ed94b7d341b43114acd1710b52.

Revert "Merge pull request #168 from alphagov/23-august-test"

---

app/models/alert.py
app/templates/components/alert.html
app/templates/views/alert.html
tests/app/main/views/test_current_alerts.py
tests/app/main/views/test_past_alerts.py
tests/app/models/test_alert.py

https://www.pivotaltracker.com/story/show/178986763
In the Admin app we plan to calculate and store "aggregate_names"
[1], but broadcasts created via the API may just have "names" [2]
that may well be understandable for display purpose (we can't tell
in advance). This change means we support both.
[1]: https://github.com/alphagov/notifications-admin/pull/4003
[2]: https://github.com/alphagov/notifications-api/pull/3312/files#diff-9999ef738a93db421762e26ea37b640815222146e1c02a4f58e8d53a7e4230baR73

Support aggregate areas with granular fallback

---

app/templates/views/index.html
app/templates/views/planned-tests.html

Note, there will be two alerts sent, one at 10 and one at 10:15
but we can potentially just tell the user it will be 1 planned test.
Will need sign off from Karl.

Add planned operator test for 9/9/21

---

app/templates/views/index.html
app/templates/views/planned-tests.html

Two alerts will be sent. One at 10:15 and one at 11:00.
Both will be cancelled after 15 minutes.
This follows the precedent of https://github.com/alphagov/notifications-govuk-alerts/pull/176
where we refer to a small number of users receiving two alerts.

Add planned operator test for 17 Sept

---

app/templates/views/index.html
app/templates/views/planned-tests.html
data.yaml

Reverts alphagov/notifications-govuk-alerts#182 and adds the two tests to the list of past alerts data.yaml file.

Take down emergency alert test from 17 sept.

---

data.yaml

This was missed in [1].
[1]: https://github.com/alphagov/notifications-govuk-alerts/commit/207d2cb1aaf377cf28f3b39bf09c49c2ce07ff5f#diff-3d941c62395536004b33c30eb9f00d6b763d619dad61fb7522b8a3299e88a981

Remove stray key in data.yaml

---

data.yaml

the alert was broadcast on 25-may-2021, but for some reason our identifier for it was 3-may-2021. Now we are fixing the identifier and leaving an empty identifier for 3-may-2021.
If user goes to url ending alerts/3-may-2021 they should be redirected to alerts/25-may-2021.
This is the first part of that work - creating an entry for that alert with correct identifier while keeping the old entry.
We will deploy this just before deploying the lambda change to support redirect for that alert, and after that lambda change is deployed, we will deploy another PR to get rid of the old entry.

Create entry for Suffolk severe alert with correct identifier 

---

README.md
data.yaml
docs/redirects.md

If someone goes to the address for the old entry, we will redirect them.
Needs to go in after https://github.com/alphagov/notifications-govuk-alerts/pull/180 and after we deploy lambda changes to support redirects.
TODO: make a note in the README that if you want to put in a redirect, you do it through Terraform/lambda in the infra repo

 Remove old entry for severe Suffolk alert

---

app/templates/views/index.html
app/templates/views/planned-tests.html

O2 will be sending Operator messages on the production network on Wednesday 29 Sept 2021.
Updates the website and banner with pre-warning of alerts.

Add 29 September O2 planned operator test message

---

app/models/alert_date.py
app/models/alerts.py
app/templates/components/alert.html
app/templates/views/past-alerts.html
tests/app/main/views/test_past_alerts.py

From this:
***
To this (grouping the alerts by date heading):
***
To this (only showing one operator test per day):

Improve grouping of past alerts

---

data.yaml

We need to change the url of this alert from
21-june-2021 to 21-jun-2021.
Therefore we duplicate the alert for a short period until we
have deployed the redirect in terraform at which point we will then
remove the old alert from the data.yaml file.

Duplicate Reading test alert to allow for redirect

---

app/celery/tasks.py
app/utils.py
tests/app/celery/test_tasks.py
tests/app/test_utils.py

This code doesn't show up if we search for "fastly", which is a
reasonable query to type.

Rename purge_cache to make it easier to find

---

app/models/alert.py
app/models/alert_date.py
app/models/alerts.py
app/templates/components/banner.html
app/templates/views/index.html
app/templates/views/planned-tests.html
planned-tests.yaml
tests/__init__.py
tests/app/main/views/test_index.py
tests/app/main/views/test_planned_tests.py
tests/app/models/test_alert.py
tests/app/models/test_alert_date.py
tests/app/models/test_alerts.py
tests/conftest.py

At the moment, whenever there is a planned test we need to update and deploy gov.uk/alerts manually.
We also update the site manually to announce upcoming public tests, like Reading.
This commit:
- automatically puts a banner on the homepage and updates the ‘Planned tests’ page whenever there is an operator test happening on a given day
- gives us a way of publishing details of upcoming public tests without having to directly edit HTML (it’s yet another YAML file)
I’ve even made it work in the case when there’s an upcoming public test, and a current operator test, like we had in the run-up to Reading.
For operator tests the banner will stay up until the end of the day. I think this is sensible since the test might not last for very long, and there might be several in one day (which we …

Automate planned tests page

---

app/models/alert.py
app/models/alerts.py
app/models/planned_test.py
app/models/planned_tests.py
app/templates/views/planned-tests.html
planned-tests.yaml
tests/app/main/views/test_index.py
tests/app/main/views/test_planned_tests.py
tests/app/models/test_alert.py
tests/app/models/test_planned_test.py
tests/conftest.py

We want to always show a standard message for operator tests on the planned tests page, not the content of the alert itself.
We also don’t want to show the names of the areas targeted by an alert, because past experience has shown that people interpret this to mean that they are more likely to receive the test than they actually are.

Hide content and areas of operator tests

---

app/templates/views/opt-out.html
app/templates/views/reasons-you-might-get-an-alert.html

The comms folk have agreed with the National Police Chiefs Council (NPCC) to not have reference to terrorist incidents when describing Emergency Alerts and have asked for that one line to be deleted.
There’s also a reference to ‘terrorism’ on the opt-out page, this pull request also removes that instance for consistency.
Before | After
---|---

Remove reference to ‘terrorist incidents’

---

requirements.txt

https://www.pivotaltracker.com/story/show/180213914
The new version of the base class:
- Reenables Celery argument checking
- Removes redundant code
See here for more details [1]. This also brings in an additional
but irrelevant change, relating to broadcast polygons.
[1]: https://github.com/alphagov/notifications-utils/pull/921

Bump utils to bring in latest NotifyCelery code

---

app/templates/views/index.html

This is good for accessibility. On GOV.UK they make the value of the title the same as the title of the YouTube video.

Add `title` to YouTube embed

---

requirements.txt

https://www.pivotaltracker.com/story/show/180693991
This brings in additional logging for the NotifyCelery base class
[1]. Although one of the other changes refers to broadcasts, the
"preview" template is only used by the Admin app.
[1]: https://github.com/alphagov/notifications-utils/blob/master/CHANGELOG.md#5130

Bump utils to 51.3.0

---

.github/pull_request_template.yml
docs/deploying.md

We have decided this is an acceptable risk:
- Most of the functionality is covered by the smoke tests and checking the Celery worker starts.
- Adding functional tests to the pipeline would mean copy / pasting config from the -aws repo.
- We wouldn't be able to prevent concurrent runs of the functional tests across pipelines [1].
- The only functionality not covered is the worker running being able to run tasks from the queue.
[1]: https://github.com/concourse/concourse/issues/2691

Add PR CD warning and known testing caveat

---

Makefile

The last 2 deploy attempts failed because the publish tasks took 23
seconds (from 2022-02-24T11:36:47Z until 2022-02-24T11:37:10Z) and 24
seconds (from 2022-02-24T12:07:19Z until 2022-02-24T12:07:43Z)
respectively.
---

Bump post-deploy task timeout from 15s to 60s

---

README.md

It was updated as per https://github.com/alphagov/notifications-govuk-alerts/commit/21469f2c6a52545f5f0ad377c7ef3f5e2c1c7f5e
---

Fix outdated python version in readme

---

README.md

https://www.pivotaltracker.com/story/show/181498273
Same as: https://github.com/alphagov/notifications-ftp/pull/368
We've agreed we're not going to fix this anytime soon because we
don't often need to run this app locally. The issue for this may
not be obvious to someone getting started, so I think it's worth
linking to it explicitly in the README.

Document ongoing issue with local development

---

Makefile

we increased the timeout in functional tests ,should do it in the deploy process too https://github.com/alphagov/notifications-functional-tests/pull/413
---

Increase gov.uk alerts build timeout

---

Makefile
package-lock.json
package.json

https://www.pivotaltracker.com/story/show/181889734
This means we can use tools like "npm audit" to look for security
vulnerabilities we definitely need to fix as they could pose a
direct risk to users. I've checked each of them with @tombye and
also against an external set of principles [^1].
[^1]: https://betterprogramming.pub/is-this-a-dependency-or-a-devdependency-678e04a55a5c

Fix incorrect group for NPM dependencies

---

app/models/alerts.py
app/models/planned_tests.py

This fixes the deprecation warning we are seeing in our logs:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load
for full details.
```
`yaml.load` has some wild features which we are not using, for example being able to create arbitrary Python objects from YAML(!): https://pyyaml.org/wiki/PyYAMLDocumentation#cb13
---

Use `yaml.safe_load` instead of `yaml.load`

---

requirements.in
requirements.txt

Brings in fixes for how URLs are linked in alerts
Also some small unrelated changes: https://github.com/alphagov/notifications-utils/compare/55.2.0...56.0.2
---

Bump utils to 56.0.2

---

Makefile

Republishing the static site currently re-renders pages for all
past alerts.
In test environments containing many test alerts, this can cause
the publish task to timeout. This change increases the wait time
to 5 minutes.
Signed-off-by: Richard Baker <richard.baker@digital.cabinet-office.gov.uk>
---

Increase publish wait time

---

app/templates/views/index.html

Make the following text revisions to the 'gov.uk/alerts' landing page:
"It’s expected to launch in autumn 2022" -> "It’s expected to launch in 2022"
"In an emergency, your phone or tablet" -> "In an emergency, your mobile phone or tablet"
---

Revise launch date and refine handset terminology

---

app/templates/views/alert.html
app/templates/views/current-alerts.html
app/templates/views/index.html
app/templates/views/mobile-network-operator-tests.html
app/templates/views/opt-out.html
app/templates/views/past-alerts.html

Content revisions:
- '/alerts' - launch date updated to "2023"
- '/opt-out' - page revised for clarity and brevity
- '/mobile-network-operator-tests' - page revised for clarity and brevity
- Breadcrumbs updated on various pages to correct casing of text.
---

EAS-454 Content update for gov.uk/alerts pages

---

README.md
app/__init__.py
app/models/alert.py
app/models/alert_date.py
app/models/alerts.py
app/models/planned_test.py
app/models/planned_tests.py
app/render.py
docs/architecture.md
docs/deploying.md
docs/redirects.md
package-lock.json
package.json
requirements.in
requirements.txt

This repository will be changing its name from 'notifications-govuk-alerts' to 'emergency-alerts-govuk'.
This PR is paired with PRs in:
notifications-broadcast-infra [#461](https://github.com/alphagov/notifications-broadcasts-infra/pull/461) (name to be changed to emergency-alerts-infra)
notifications-cbc-proxy [#120](https://github.com/alphagov/notifications-cbc-proxy/pull/120) (name to be changed to emergency-alerts-cbc-proxy)
---

EAS-475 Repository to change name

---

app/assets/stylesheets/_govuk_frontend.scss
app/templates/_layout.html
app/templates/views/index.html
tests/app/main/views/test_index.py

Changes to be deployed on Jan 30, 2023:
----
1. Status box on index page that shows "There are no current alerts" if there are no alerts.
2. Phase banner shows BETA and trialling text.
---

Jan 30 2023 Deployment - No alerts status box, BETA banner

---

app/assets/stylesheets/_govuk_frontend.scss
app/templates/_layout.html

Changes to the header in the layout used across all pages of the application, to:
- Service Name - "Emergency Alerts" added to the centre of the GOVUK Header
- Beta Banner - "This is a new service that is being trialled.", added with the tag "BETA" to pages, using the GOVUK phase banner component.
These are in line with new content requirements, stipulated as part of the new content design wireframes/prototypes.
---

Layout header modifications to fit new content designs

---

app/render.py
app/templates/views/alert.cy.html
app/templates/views/current-alerts.cy.html
app/templates/views/how-alerts-work.cy.html
app/templates/views/index.cy.html
app/templates/views/index.html
app/templates/views/past-alerts.cy.html
app/templates/views/planned-tests.cy.html
app/templates/views/system-testing.cy.html
tests/app/main/test_local_links.py

This PR changes the Welsh index page route to /alerts/about.cy, so that all pages are under the /alerts/ route, which will fix the 404 issue in the staging environment.
---

Update Welsh index page to /alerts/about.cy

---

app/templates/components/alert.html
app/templates/views/planned-tests.cy.html
app/templates/views/planned-tests.html
tests/app/main/views/test_past_alerts.py
tests/app/main/views/test_planned_tests.py
tests/app/models/test_alerts.py

Replace location headings with 'Mobile network operator test' for all appearances of an MNO test, including in planned tests and when displayed in past alerts. This does not interfere with actual alerts (or public tests), where the actual alert location will be displayed when planned, when current, and when in past alerts.
---

Replace location headings with 'Mobile network operator test'

---

app/templates/_layout.html

The following contains the feedback link to be added to the phase banner, 24 hours following the release of the NTM, and after the national survey link below the status box has been pulled, such that feedback can continue to be provided for the trialled service even following the launch. The national survey link has been added in a PR from the [EAS-553-national-survey](https://github.com/alphagov/emergency-alerts-govuk/tree/EAS-553-national-survey) branch.
**This has been drafted as it is not to be deployed until after the survey link has been pulled as mentioned above.**
---

Add feedback link to phase banner

---

planned-tests-dev.yaml
planned-tests-preview.yaml
planned-tests-staging.yaml
planned-tests.yaml

In the Welsh planned alert notifications, the Welsh text should come first.
---

Correction to the Welsh/English order of planned alert text

---

app/templates/views/index.cy.html
app/templates/views/index.html
tests/conftest.py

Display multiple status box permutations when applicable, as opposed to overriding by precedence, in order to ensure that the announcement status box is still displayed, even if there is also a current alert and/or a service test (i.e., status boxes stacked atop one another in order of precedence).
---

Display multiple status box permutations when applicable

---

app/models/alert_date.py
app/templates/components/banner.html
app/templates/views/announcements.cy.html
app/templates/views/announcements.html
planned-tests-dev.yaml
planned-tests-preview.yaml
planned-tests-staging.yaml
planned-tests.yaml
tests/app/main/views/test_announcements.py
tests/app/models/test_alert_date.py

To add the time to the landing page banner and announcement page, the following changes were made:
- Add a method to convert the meridiem indicator to lowercase
- Use new alert_date method to display date & time in banner and announcement templates
- Update alert-date and announcements test files to reflect the extra 'time' text
- Update planned test times in the dev, preview, staging and prod YAML files (in UTC)
---

EAS-862 Add National Test time to banner and announcement

---

app/templates/views/index.cy.html
app/templates/views/index.html
planned-tests-dev.yaml
planned-tests-preview.yaml
planned-tests-staging.yaml
planned-tests.yaml

Expires the announcement at 3:05. Announcements are also superseded in the status box by current alerts, meaning that the announcement will be hidden for the remainder of time that it remains in the site, before being stripped out when the alert is taken down (presumably after 3:05)
---

NTM Announcement Expiry

---

app/templates/_layout.html
app/templates/views/index.cy.html
app/templates/views/index.html

The following are display changes to be shown on the day of the NTM - i.e., the national survey and temporary removal of the feedback link in the phase banner. The big diff is because the index content needed to be wrapped to make the national survey appear okay.
**This is not to be merged in until then.**
---

Display Changes for NTM

---

app/templates/views/announcements.cy.html
app/templates/views/announcements.html
app/templates/views/current-alerts.cy.html
app/templates/views/current-alerts.html
app/templates/views/how-alerts-work.cy.html
app/templates/views/how-alerts-work.html
app/templates/views/index.cy.html
app/templates/views/index.html
app/templates/views/past-alerts.cy.html
app/templates/views/past-alerts.html
app/templates/views/planned-tests.cy.html
app/templates/views/planned-tests.html
app/templates/views/privacy-notice.html
app/templates/views/service-tests.cy.html
app/templates/views/service-tests.html
app/templates/views/system-testing.cy.html
app/templates/views/system-testing.html
tests/app/main/views/test_index.py
tests/app/main/views/test_service_tests.py

Complete removal of MNO test display on frontend.
Note this has mostly been stripping out of components that will display MNO tests from the jinja, and removal of tests that specifically checked for the presence of MNO tests. This should be a temporary fix.
---

Complete removal of MNO test display

---

Dockerfile.eas-govuk-alerts
Makefile
app/config.py
scripts/start-govuk.sh

The AWS environments will need an instance that runs a celery worker to handle messages on the `<env>-govuk-alerts` SQS queue.
This PR should not be merged until we have the Gov.uk/Alerts pipeline fully operational. Test can be accomplished by tagging the commit of this PR and running the pipeline manually to deploy to the required environment.
---

EAS-1005 Add script for starting govuk-alerts celery worker

---

app/config.py

The original config needs to be restored to maintain compatibility with the Concourse pipelines until such time that we can move away from Concourse completely.
---

EAS-1005 Revert config to fix concourse pipelines

---

requirements.in
requirements.txt
scripts/start-govuk.sh

Adding flask publish-with-assets to start script of the govuk ECS service
---

adding flask publish to start script

---

Dockerfile.eas-govuk-alerts

Create empty environment.sh file to allow the docker image to build
---

EAS-450 Create environment.sh file to dockerfile

---

.codepipeline/buildspec-govuk-build.yml

Removing checking out to latest tag within the build step of code pipeline
---

removing tag functionality from build pipeline

---

app/commands.py
app/utils.py

- Different file types should be read with different encodings
- Python's mime_type parser uses a legacy type (application/javascript); this is changed to text/javascript on the fly
---

EAS-1070 Fix asset mime types

---

app/utils.py

The native python 3.9 mimetype package doesn't handle all file types in the govuk-alerts application. This PR implements a simple custom mapper, covering the file types found in the /dist folder.
---

EAS-1070 Handle mimetypes in govuk-alerts

---

app/celery/tasks.py
scripts/healthcheck.sh

Celery should respond to the period task to update the health-check timestamp file, used by the AWS govuk-alerts container.
---

EAS-1089 Implement govuk-alerts healthcheck celery beat task

---

app/templates/_layout.html
app/templates/views/404.html
app/templates/views/alert.cy.html
app/templates/views/alert.html
app/templates/views/announcements.cy.html
app/templates/views/announcements.html
app/templates/views/current-alerts.cy.html
app/templates/views/current-alerts.html
app/templates/views/how-alerts-work.cy.html
app/templates/views/how-alerts-work.html
app/templates/views/index.cy.html
app/templates/views/index.html
app/templates/views/past-alerts.cy.html
app/templates/views/past-alerts.html
app/templates/views/planned-tests.cy.html
app/templates/views/planned-tests.html
app/templates/views/privacy-notice.html
app/templates/views/service-tests.cy.html
app/templates/views/service-tests.html
app/templates/views/system-testing.cy.html
app/templates/views/system-testing.html

Make relative links to paths outside of /alerts absolute, given that we're no longer running on infrastructure that will allow us to make relative links to gov.uk.
---

Make relative links to paths outside of /alerts absolute

---

app/assets/stylesheets/_extensions.scss
app/templates/views/privacy-notice.html
scripts/docker-build.sh

EAS-914
- The content of the Privacy notice page (https://www.gov.uk/alerts/privacy-notice) has been updated to reflect the https://www.notifications.service.gov.uk/privacy page.
EAS-1081
- The content changes also include fixes to the 'mailto:' links on the email references in the body text.
---

EAS-914 EAS-1081 Privacy Notice update

---

app/templates/views/system-testing.html
tests/app/main/views/test_system_testing.py

Remove " to assess improvements that have been made to the service." from the first paragraph of the system testing page to reflect content designs.
---

fix operator tests content first paragraph

---

.github/pull_request_template.yml
.github/workflows/on-pr-into-main.yml
app/__init__.py
app/config.py
app/models/planned_tests.py
app/utils.py
manifest.yml.j2
pytest.ini

The HOST variable is used to distinguish between running locally and on the hosted infrastructure (i.e. AWS). This variable can therefore take one of the following values:
HOST = [ local | hosted | test ]
"local" indicates that the service will be configured for running on a local machine. "hosted" is intended for use when the service is running on the AWS-hosted infrastructure. "test" provides a special set of configuration values that are used by the unit, integration and functional tests.
The environment variable ENVIRONMENT is used to tell the service which set of config values to take up, and can be set to one of the following values:
ENVIRONMENT = [ local | development | preview | staging | production ]
A value of "local" indicates that the service will be running on the development …

EAS-1576 Add config for local running

---

requirements.txt

emergency-alerts-utils stipulates a higher version of the `phonenumbers` package than this repository currently allows. This needs to be updated accordingly here.

Bump allowed phonenumbers version as utils now stipulates it

---

.codepipeline/buildspec-govuk-build.yml
.codepipeline/buildspec-govuk-deploy.yml
.codepipeline/deploy-service.sh
Dockerfile.eas-govuk-alerts
app/config.py
scripts/start-govuk.sh

This PR amends the Dockerfiles and buildspec.yml files to enable dynamic resource prefixes when referring to (primarily) the appropriate ECR repository to use for the base image. This way, modifications can be made to the utils package and deployed to the particular user's development environment, and it will be referenced appropriately when building other application components (e.g., Admin, API) using it.

EAS 1736 Multi Tenant Dev - tenant prefixing

---

app/render.py
app/templates/components/alert.html
app/utils.py
tests/app/main/views/test_current_alerts.py
tests/app/main/views/test_past_alerts.py
tests/app/test_utils.py

Simple implementation of a capitalisation util to ensure any alerts displayed have the first character of their display name capitalised (sometimes they will not be when retrieved from the database, for instance when using custom polygons).

Implementation of capitalize util and usage for alerts

---

app/render.py
app/utils.py
requirements.in
requirements.txt
tests/app/test_utils.py

Upgrade Flask, Jinja2 and other packages to pull in the latest version of Werkzeug (required to be upgraded to latest version https://github.com/alphagov/emergency-alerts-api/security/dependabot/2)

EAS-2028 Apply version upgrades

---

app/render.py
app/templates/components/alert.html
app/templates/views/alert.cy.html
app/templates/views/alert.html
app/utils.py
tests/app/main/views/test_current_alerts.py
tests/app/test_utils.py

The removal of redundant detail in Custom Area names when displayed on gov.uk/alerts and the relevant tests for this. 
For example, "5km around the easting of 530111.0 and the northing of 171161.0, in Lambeth" is displayed as "an area in Lambeth".

EAS-2030 Simplification of Custom Area names displayed

---

app/models/alert_date.py

Replaced the use of the deprecated datetime.utcnow() method with
datetime.now(datetime.timezone.utc) to create an aware datetime object
representing the current UTC time.

Avoid utcnow() which is deprecated

---

Makefile
app/celery/tasks.py
app/utils.py
tests/app/celery/test_tasks.py

As per the docs: "The number of worker processes/threads can be changed using the --concurrency argument and defaults to the number of CPUs available on the machine."
The `--autoscale` argument keeps a minimum of 1 process, but permits scaling up to 8 processes to handle queued tasks.

EAS-1055 Log broadcast-event-id with each page upload

---

Makefile

By ensuring that we have only one Celery worker instance, we can prevent non-deterministic uploads from near simultaneous build tasks and also ensure tasks are processing in order.

EAS-2570 Prevent concurrent website uploads

---

app/assets/stylesheets/components/atom.scss
app/assets/stylesheets/feed.xsl
app/assets/stylesheets/feed_cy.xsl

This will fix the noticeable issue on Staging, where long strings of characters without whitespace overflow the page width.

EAS-2552 Force break on long strings with no whitespace

---

app/assets/stylesheets/feed.xsl
app/assets/stylesheets/feed_cy.xsl

Order the view entries so that we see the most recent first (opposite to the way atom feeds are generated).

Order HTML view entries

---

app/assets/stylesheets/feed.xsl
app/assets/stylesheets/feed_cy.xsl

Logo link on Prod was incorrect - this change should link to "https://www.gov.uk" now (and also work on the lower environments).

Fix govuk logo link

---

.codepipeline/buildspec-govuk-build.yml

This PR removes the tag checkout in the `buildspec.yml`. It has been agreed that this is a historical artefact, from a time where CodePipeline was not capable of sourcing a particular commit hash, so there was no way to actually run a pipeline with a non-HEAD commit - or even a commit that wasn't latest@main, because generally it's inadvisable to change the source branch of the pipeline, as that's a permanent configuration difference that does class as a form of infra drift.
Nowadays (and as of [November 2023](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-codepipeline-pipeline-execution-source-revision-overrides/)) you can use the `source revision override` feature to run CodePipeline on an arbitrary commit hash. Given our main concern was facilitating quick rollbacks or …

Remove checkout to tag in Buildspec

---

.github/workflows/on-pr-into-main.yml

This PR adds the ability for PR checks to be run on pull requests to the main branch even when they are in a draft state. Currently, they only run when the PR is in a "Ready for review" state, which isn't very helpful in instances where you want an easy way of checking the build status of your work on the branch itself, without indicating to other people that you would like your PR to be reviewed.
Corresponding PRs will be made for Utils, API, Admin, and gov.uk/alerts

Add PR checks even when a PR is in a draft state

---

app/main.py

This fixes the stylesheets for Atom / XML rendering locally. We set a content type on the objects uploaded to S3 already. Browsers seem strict on the Content-Type before interpreting the associated sheet which results in this without:

Provide the correct MIME type for Atom/XML in local

---

app/__init__.py
app/celery/tasks.py
app/commands.py
app/notify_client/alerts_api_client.py
requirements.in
requirements.txt
tests/app/celery/test_tasks.py

> **Requires https://github.com/alphagov/emergency-alerts-utils/pull/112 and https://github.com/alphagov/emergency-alerts-api/pull/229**
As title - API will now call GovUK for naturally finished alerts and expects to receive an acknowledgement from GovUK when it has finished a publishing event.

EAS-2548: GovUK: Call API's /acknowledge after publishing

---

app/templates/components/extended_alert.html
tests/app/main/views/test_current_alerts.py
tests/app/main/views/test_past_alerts.py

This PR adjusts the H2 text for the extended alert, displayed on 'Current alerts' page if there's only one current alert. The tests have also been adjusted accordingly.

Adjusts extended alert H2 & tests accordingly

---

Dockerfile.eas-govuk-alerts
Makefile
gulpfile.js
package-lock.json
package.json
requirements.in
requirements.txt

This PR:
- Bumps Node to 22.18.0
- Bumps any vulnerable Node/PyPi packages

ECR Dependency Scan Package Bump

---

app/models/planned_test.py
app/templates/components/banner.html
app/templates/views/announcements.cy.html
app/templates/views/announcements.html
planned-tests-dev.yaml
planned-tests-preview.yaml
planned-tests-staging.yaml
planned-tests.yaml
tests/app/main/views/test_announcements.py
tests/app/main/views/test_index.py
tests/app/main/views/test_system_testing.py
tests/conftest.py

This PR updates the planned tests yaml files to update the content within announcement banner, and to ensure the banner links to announcements page.
Additionally, if `starts_at_datetime_in_welsh`  or `areas_in_welsh` are present in `planned-tests.yaml` then they are displayed on `announcements.cy.html`, otherwise the default attributes in English are displayed.

EAS-2278 Add national test content

---

app/templates/views/public-testing.cy.html
app/templates/views/public-testing.html
planned-tests-dev.yaml
planned-tests-preview.yaml
planned-tests-staging.yaml
planned-tests.yaml

This PR adds a link regarding alternative accessible formats, to the 'Public testing' pages in English and Welsh, and adjusts the finish time for the planned-tests banner.

EAS-2784 Adds link to public testing pages

---

app/models/planned_test.py
app/templates/components/banner.html
app/templates/views/opting-out.cy.html
app/templates/views/opting-out.html
app/templates/views/public-testing.cy.html
app/templates/views/public-testing.html
planned-tests-dev.yaml
planned-tests-preview.yaml
planned-tests-staging.yaml
planned-tests.yaml
tests/app/main/views/test_announcements.py
tests/app/main/views/test_index.py
tests/app/main/views/test_system_testing.py
tests/conftest.py

This PR consists of the following:
- adds the `planned_tests_link` property to PlannedTest class, sets default link to be to `announcements` page, and for the upcoming tests it is set to `public-testing` page in `planned-tests.yaml` files
- adds link to "test alert" on `public-testing` pages, to `announcements` page
- Adjusts opting out guidance

National test adjustments

---

Makefile

Simple stuff; just adding a standalone Makefile command for running Flask in debug mode, rather than using environment variables and such when developing locally.

Add Makefile command for running Flask in debug mode

---

app/assets/stylesheets/feed.xsl

Should fix the feed page appearing blank in Firefox, due to an XSLT typo which Chrome overlooks.
Available in my hosted env: https://d1hux4sl1zpub5.cloudfront.net/alerts/feed.atom
Should resolve https://bugzilla.mozilla.org/show_bug.cgi?id=1987368 / https://github.com/webcompat/web-bugs/issues/175872

Fix sort syntax in atom feed XSLT for Firefox

---

.github/dependabot.yml

See https://github.com/alphagov/emergency-alerts-govuk/network/updates/1114974142 / #427

EAS-2767: GovUK: Ignore requirements_local_utils.txt in Dependabot
