alphagov/emergency-alerts-govuk

src/index.html, src/planned-tests.html
~~**Do not merge this PR until Friday 21 May**~~
This PR updates the planned alert page content. It replaces details of Thursday’s test with the East Suffolk test on Tuesday 25 May.
=> [MERGE ON 21 MAY] Update planned alert content

src/planned-tests.html
Update planned test content to simplify the information about the number of test alerts being sent.
=> Update planned test content

lib/alert.py, src/alert.html, tests/conftest.py, tests/test_alert.py, tests/test_alerts.py, tests/test_data_yaml.py
https://www.pivotaltracker.com/story/show/178198202
Please see the commit messages for more details.
| Alert page  | Home page |
| ------------- | ------------- |
| <img width="708" alt="Screenshot 2021-05-24 at 10 51 16" src="https://user-images.githubusercontent.com/9029009/119331220-070b9480-bc7f-11eb-8b31-26967c35e246.png"> | <img width="431" alt="Screenshot 2021-05-24 at 10 51 21" src="https://user-images.githubusercontent.com/9029009/119331246-0f63cf80-bc7f-11eb-8307-008f6481d078.png"> |
=> Use 'sent' property to show alerts early

data.yaml
=> Temporarily modify alert timestamps for dry run

data.yaml
This reverts commit d7165857069c1a6332bd698cea9c9fc4434599bc.
=> Revert "Temporarily modify alert timestamps for dry run"

src/current-alerts.html, src/past-alerts.html
This PR makes some small content changes to the current and past alerts pages.
=> Update content for the current and past alerts pages

src/privacy-notice.html
Same as we do for the Civil Contingencies Act
=> Add link to PECR legislation

src/opt-out.html
Small content update for the opt out page.
=> Update opt out content for operator tests

src/opt-out.html
This PR adds a missing full stop and updates the content to make the opt out instructions more explicit.
=> Fix punctuation, add final intstruction

src/planned-tests.html
The date of the test has moved.
=> Update date of Reading test

src/opt-out.html
I changed the name of this class in the CSS but forgot to update it in the HTML.
=> Reflect renamed class

src/index.html, src/planned-tests.html
=> Add details of planned tests to the homepage and planned tests page

src/index.html, src/planned-tests.html
=> Fix date of planned test

tests/conftest.py, tests/src/test_current_alerts.py, tests/src/test_index.py, tests/src/test_past_alerts.py, tests/test_local_links.py
Test that all links to `/alerts` pages are correct. Part of this story:
https://www.pivotaltracker.com/story/show/177597156
=> Test local links in pages

src/planned-tests.html
=> Add time of tomorrow’s test

src/index.html, src/planned-tests.html
=> Add next Tuesday’s test to the planned tests page

src/index.html, src/planned-tests.html
=> Remove the 18 June planned test

templates/_layout.html
In case people have missed it elsewhere, this gives us another place to catch their attention.
=> Add feedback survey to footer

src/index.html, src/planned-tests.html
This should not be deployed until the end of day on Thursday 8 July.
=> Add Friday 9 July test to planned tests page

data.yaml, src/index.html, src/planned-tests.html
Not to be merged until after 2pm on Friday 9 July
=> Move Friday 9 July planned test to past alerts

src/index.html, src/planned-tests.html
Should be deployed end of the day on 13 July.
***
***
=> Add 14 July operator test to site

data.yaml, src/index.html, src/planned-tests.html
Should be deployed end to the day on July 14
=> Move 14 July planned test to past alerts page

src/index.html, src/planned-tests.html
Should be merged this evening (Tuesday) or first thing tomorrow (Wednesday).
=> Add 28 July operator test to planned alerts page

src/index.html, tests/src/test_index.py
https://www.pivotaltracker.com/story/show/178774818
=> Fix current alert banner not showing

data.yaml, lib/alert.py, lib/alerts.py, lib/utils.py, src/alert.html, templates/components/alert.html, tests/conftest.py, tests/lib/test_alerts.py, tests/lib/test_utils.py, tests/src/test_current_alerts.py, tests/src/test_past_alerts.py
https://www.pivotaltracker.com/story/show/178774818
While I'd like this to go in, we could also just use it for reference if we
think there's value in delaying the implementation.
Please see the commit messages for more details.
=> Filter alerts to ensure they're in the UK

data.yaml
https://www.pivotaltracker.com/story/show/178986763
This is so it matches the data we'll be returning in the API.
=> Tweak reading area for past broadcast

app/templates/views/index.html
The existing content is out of date.
We’ve been waiting for confirmation that we can change the expected launch window from 'summer' to 'autumn'. We got that confirmation today.
=> Update launch window from 'summer' to 'autumn'

app/templates/views/index.html, app/templates/views/planned-tests.html, data.yaml
=> Add planned test for 10 September and add alerts that were sent on 9 September

app/templates/views/index.html, app/templates/views/planned-tests.html, data.yaml
Review commit by commit
Not to be merged until after testing is complete today
=> Remove planned tests

Makefile
https://www.pivotaltracker.com/story/show/179482902
Relates to: https://github.com/alphagov/notifications-broadcasts-infra/pull/313
=> Support deploying to the Preview environment

app/templates/views/index.html, app/templates/views/planned-tests.html, data.yaml
Reverts alphagov/notifications-govuk-alerts#188
=> Revert "Add 29 September O2 planned operator test message"

README.md
https://www.pivotaltracker.com/story/show/179659713
Related to: https://github.com/alphagov/notifications-broadcasts-infra/pull/324
This is going to continue for the foreseeable future so we should
caveat the link to it here to reflect that.
=> Document ongoing issue with Staging environment

app/templates/views/index.html
This PR updates the launch window for Emergency Alerts. The wording has been OK-ed.
=> Update launch date

app/templates/views/opt-out.html, app/templates/views/reasons-you-might-get-an-alert.html
This reflects the main uses of the service.
---
=> Update examples to say ‘extreme weather’

Makefile, README.md, app/models/alerts.py, app/models/planned_tests.py
https://www.pivotaltracker.com/story/show/181498273
Please review commit by commit.
=> Fix to local development with Flask

app/templates/views/index.html
=> Update expected launch date to summer 2022

app/templates/views/index.html
Update expected launch date to ‘autumn 2022’
---
=> Update expected launch date to autumn 2022

app/templates/views/index.html
Pull request opened to run concourse checks on PR 228.
---
=> Revise launch date and refine other text

app/templates/views/alert.html, app/templates/views/current-alerts.html, app/templates/views/index.html, app/templates/views/mobile-network-operator-tests.html, app/templates/views/opt-out.html, app/templates/views/past-alerts.html
=> Concourse test pr 230

app/templates/views/opt-out.html
=> remove unnecessary text

app/templates/views/announcements.cy.html
Finalised Welsh translations for the Announcements page.
---
=> Announcements page finalised Welsh translations

app/templates/views/index.cy.html, app/templates/views/index.html
=> remove youtube video

app/templates/views/index.cy.html, app/templates/views/index.html
Textual content changes for EA live launch
---
=> Last minute content changes

app/models/alert_date.py, app/templates/components/banner.html, app/templates/views/index.cy.html, app/templates/views/index.html, planned-tests-dev.yaml, planned-tests.yaml
=> New youtube video

planned-tests-preview.yaml, planned-tests-staging.yaml
=> change test date

planned-tests-preview.yaml, planned-tests-staging.yaml, planned-tests.yaml
=> fixing the data again

app/templates/views/index.cy.html, app/templates/views/index.html
Update the 'What you need to do' section in accordance with Apr 2023 content change requirements. 
---
=> Update the 'What you need to do' section

app/models/alerts.py, tests/app/models/test_alerts.py
=> only display service tests on service tests page if active

README.md
I was trying to get this to run locally and found I needed to install the proj and geos to get things working.
---
=> Mention proj and geos in README

app/models/alert.py, tests/app/main/views/test_past_alerts.py, tests/app/models/test_alert.py
=> MNO tests no longer appear in past alerts

.codepipeline/buildspec-govuk-deploy.yml
=> Changing the script location

Dockerfile.eas-govuk-alerts
=> Updating the dockerfile for govukalerts

.codepipeline/buildspec-govuk-build.yml
=> Updating the tag pointer

.codepipeline/buildspec-govuk-build.yml
=> Passing account number to dockerfile

.codepipeline/buildspec-govuk-tests.yml, Dockerfile.eas-govuk-alerts, scripts/start-govuk.sh
=> Reduce the repeated code

scripts/start-govuk.sh
=> Adding option of debug flag

scripts/start-govuk.sh
=> Adding a sleep to the debug call

app/utils.py
=> Updating govuk to use client for uploads

Dockerfile.eas-govuk-alerts, app/utils.py
Creating eas user within the dockerfile
---
=> Eas 449 eas user creation

app/config.py
=> Adding hostname to API config

scripts/start-govuk.sh
=> Switching the start order of the services

app/commands.py, app/utils.py
Css and javascript files still require byte encoding when uploaded with s3.put_object
---
=> EAS-1070 Upload css/javascript files

Dockerfile.eas-govuk-alerts
=> Adding healthcheck script

app/assets/stylesheets/_extensions.scss, app/templates/views/privacy-notice.html
The previous commit is reverted and only the mailto links are fixed.
---
=> EAS-1081 Revert previous commit and fix mailto links

app/config.py
=> Predefined celery queues to match with SQS infra

app/config.py
=> change broker url to not require sigv4

app/models/alert.py, app/templates/views/announcements.cy.html, app/templates/views/announcements.html, app/templates/views/current-alerts.cy.html, app/templates/views/current-alerts.html, app/templates/views/how-alerts-work.cy.html, app/templates/views/how-alerts-work.html, app/templates/views/index.cy.html, app/templates/views/index.html, app/templates/views/past-alerts.cy.html, app/templates/views/past-alerts.html, app/templates/views/privacy-notice.html, app/templates/views/system-testing.cy.html, app/templates/views/system-testing.html, tests/app/main/views/test_system_testing.py, tests/app/models/test_alerts.py
=> Update system testing page content and display service tests

.github/workflows/on-pr-into-main.yml, .github/workflows/pr-checks.yml, .pre-commit-config.yaml, requirements_for_test.txt
Add github action definition to run basic checks when a PR is raised
---
=> EAS-1202 Add pr checks

.codepipeline/buildspec-govuk-build.yml, .codepipeline/buildspec-govuk-deploy.yml
Adding tagging to be pushed with the image in order to have the pipeline execution ID and commit ID included in the image
---
=> adding correct tagging commands

.codepipeline/buildspec-govuk-build.yml
=> adding image tagging

.github/dependabot.yml
=> Add basic daily dependabot checks

scripts/start-govuk.sh
=> Adjusting healthcheck

scripts/start-govuk.sh
=> Updating the healthcheck debug flag

scripts/start-govuk.sh
=> Adding do to the script

README.md
Linked to confluence pages recently created to consolidate the local development environment setup instructions.
=> EAS 1857 Updated README

app/config.py, scripts/docker-build.sh, scripts/start-govuk.sh
This PR consists of replacement of hardcoded AWS region references, where appropriate, instead now using the environment variable in task definition.
=> EAS-2401 Replaced hardcoded regions

app/models/alert_date.py
Correct a typo & Fix deprecated use of `utcnow`.
=> 2025-01-24 External contributions - Correct a typo & Fix deprecated use of utcnow

app/templates/views/current-alerts.cy.html, app/templates/views/current-alerts.html, app/templates/views/how-alerts-work.cy.html, app/templates/views/how-alerts-work.html, app/templates/views/past-alerts.cy.html, app/templates/views/past-alerts.html, app/templates/views/system-testing.cy.html, app/templates/views/system-testing.html, tests/app/main/views/test_system_testing.py
Apply updates as detailed in the ticket https://gds-ea.atlassian.net/browse/EAS-2428.
=> EAS-2428 English and Welsh updates

app/assets/stylesheets/feed.xsl, app/assets/stylesheets/feed_cy.xsl
Hardcode feed titles to avoid mixing Welsh/English.
=> EAS-2552 Fix feed titles

requirements.in, requirements.txt
=> EAS-2692 Force Werkzeug version bump

app/templates/views/index.html
Fixing a mistake in site content.
=> EAS-Fix GOVUK site content
